name: cert-manager
server: https://acme-v02.api.letsencrypt.org/directory
preferredChain: "ISRG Root X1"
email: ""
privateKeySecretRef:
  name: cert-manager-private-key
solvers:
  - http01:
      ingress:
        class: nginx
